### PR TITLE
initial: add makimaprjkt° as provide chain-registry

### PR DESCRIPTION
**Pull request by sxlmnwb**
- seeds
- persistent_peers
- rpc
- grpc
- rest
- state_sync

### CODE REVIEW

**Review by RaulBernal — APPROVED** [review]
Looks good! thanks

**Comment by RaulBernal** [comment]
@zakarialounes Can you close this pull request, sync the last changes and make the PR again please? 
There some conflicts that I can't resolve from WEB UI

**Comment by RaulBernal** [comment]
Sorry please re-sync your fork and send again the PR, too much conflicts there 🙏

**Comment by zakarialounes** [comment]
> @zakarialounes Can you close this pull request, sync the last changes and make the PR again please? There some conflicts that I can't resolve from WEB UI

/forwardTo @sxlmnwb

**Pull request closed without merging**
