### PR TITLE
Attending IBC Security Advisory Huckleberry

### PR DESCRIPTION
**Pull request by RaulBernal**
- Bump IBC-go to v6.1.1
- Bump CometBFT to v0.34.28

### CODE REVIEW

**Comment by RaulBernal** [comment]
Tested in DEVNET-1

**Comment by RaulBernal** [comment]
LGTM - Testnet test passed at DEVNET-1 @atmoner @TJ-BitCanna @bcnajohan

**Review by atmoner — APPROVED** [review]
Good for me!

**Review by TJ-BitCanna — APPROVED** [review]
Looks good :)

**Review by TJ-BitCanna — APPROVED** [review]
Looks good :)

**Pull request merged**
