### PR TITLE
Second Joint: Liquidity module

### PR DESCRIPTION
**Pull request by faddat**
Seems that all that's needed here, is to do the type of adapterdoo seen in export.go for the IBCKeeper.

There may be some other sylistic touches needed:

* upgrade handler
* audit by other Notional team members, quicksilver and iqlusion
* all the tests we can cram in

Thanks for your willingness to check it out.

BCNA shall liquid sers, and stakers shall not need to unbond.

------

image

100% Ghanian Sativa, accept no imitations

### CODE REVIEW

**Comment by RaulBernal** [comment]
Good work so far!
Let me elaborate the upgrade handler when is ready

**Comment by faddat** [comment]
This has been updated to reflect main, too. 

So, now both of these have the ica support from main, as well as the removal of jaekwon/testify.

**Review by RaulBernal — COMMENTED** [review]
It seems good BUT maybe it does't work because there is a small migration from ibc/go v3 to ibc/go v4. I will check anyway. BIG THANKS!

**Comment by faddat** [comment]
ahhhhhhhhhhhh

yeah so, you're right. 

there is definitely that. :D

**Comment by RaulBernal** [comment]
Hello @faddat @vuong177 thanks for collaborating :) 
I've compiled the code and I can't see the CLI module interaction, look: 

Let's check I'm in your branch:
```
git checkout
Your branch is up to date with 'origin/liquidity-module'.

```
Let's check IQLusioninc module is there:

```
bcnad version --long  | grep liquidity-staking
- github.com/iqlusioninc/liquidity-staking-module@v1.0.0 => github.com/notional-labs/liquidity-staking-module@v0.0.3-0.20220903210408-38ba22eebbef
```
And try:
```
bcnad query liquidity
Error: unknown command "liquidity" for "query"
Usage:
  bcnad query [flags]
  bcnad query [command]

Aliases:
  query, q

Available Commands:
  account                  Query for account by address
  auth                     Querying commands for the auth module
  authz                    Querying commands for the authz module
  bank                     Querying commands for the bank module
  bcna                     Querying commands for the bcna module
  block                    Get verified data for the block at given height
  distribution             Querying commands for the distribution module
  evidence                 Query for evidence by hash or for all (paginated) submitted evidence
  feegrant                 Querying commands for the feegrant module
  gov                      Querying commands for the governance module
  ibc                      Querying commands for the IBC module
  ibc-transfer             IBC fungible token transfer query subcommands
  interchain-accounts      interchain-accounts subcommands
  mint                     Querying commands for the minting module
  params                   Querying commands for the params module
  slashing                 Querying commands for the slashing module
  staking                  Querying commands for the staking module
  tendermint-validator-set Get the full tendermint validator set at given height
  tx                       Query for a transaction by hash, "<addr>/<seq>" combination or comma-separated signatures in a committed block
  txs                      Query for paginated transactions that match a set of events
  upgrade                  Querying commands for the upgrade module
  ```

**Comment by RaulBernal** [comment]
Definitely we decided to close this PR in favor to develop the branch https://github.com/BitCannaGlobal/bcna/tree/SDK_046
We hope to see your collaboration there.

BTW @faddat @vuong177 there is an issue in the current PR because liquidity module can't be managed in CLI
https://github.com/BitCannaGlobal/bcna/pull/63#issuecomment-1250817748

**Comment by RaulBernal** [comment]
See the last comments :)

**Pull request closed without merging**
